[TO REVERT] Test matrix commit status behavior

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -7,278 +7,27 @@ env:
   IMAGE_ID: $IMAGE_ID
 
 steps:
-  - label: Lint
-    key: lint
-    command: |
-      .buildkite/commands/install-node-dependencies.sh
-      echo '--- :eslint: Lint'
-      npm run lint
-    plugins:
-      - $CI_TOOLKIT_PLUGIN
-      - $NVM_PLUGIN
-    notify:
-      - github_commit_status:
-          context: Lint
-
-  - label: Unit Tests
-    key: unit_tests
-    command: |
-      .buildkite/commands/install-node-dependencies.sh
-      echo '--- :npm: Run Unit Tests'
-      npm run test
-    plugins:
-      - $CI_TOOLKIT_PLUGIN
-      - $NVM_PLUGIN
-    notify:
-      - github_commit_status:
-          context: Unit Tests
-
-  - label: Experiment Windows Unit Tests
-    # Reference: https://github.com/Automattic/studio/pull/76#issuecomment-2162689679
-    skip: Disabled till we solve Windows-specific test failures
-    command: |
-      bash .buildkite/commands/install-node-dependencies.sh
-      echo '--- :npm: Run Unit Tests'
-      npm run test
-    agents:
-      queue: windows
-    plugins:
-      - $CI_TOOLKIT_PLUGIN
-      - $NVM_PLUGIN
-    notify:
-      - github_commit_status:
-          context: Windows Unit Tests
-
   # Notice that we use the queue name (matrix value) in the label.
   # We could have added values for queue and label, but that would have resulted in 'macOS + windows' and 'Windows + mac' combinations, which we don't want.
   # Buildkite offers an option to remove those combinations, but the overhead in code readability did not seem worth the visual effect in the build page.
   # See https://buildkite.com/docs/pipelines/build-matrix#removing-combinations-from-the-build-matrix
-  - label: E2E Tests on {{matrix}}
-    key: e2e_tests
+  - label: Check Matrix Behavior with {{matrix}}
     command: |
-      # call with bash explicitly because we run this on Windows, too
-      bash .buildkite/commands/install-node-dependencies.sh
-      echo '--- :package: Package app for testing'
-      npm run package
-      echo '--- :playwright: Run End To End Tests'
-      npm run e2e
-    artifact_paths:
-      - test-results/**/*.zip
-    plugins:
-      - $CI_TOOLKIT_PLUGIN
-      - $NVM_PLUGIN
+      echo "Waiting {{matrix}}s"
+      sleep {{matrix}}
+      if [[ {{matrix}} -lt 30 ]]; then
+        echo "Failing first runs of the matrix"
+        exit 1
+      else
+        echo "Succeeding subsequent runs of the matrix"
+        exit 0
+      fi
     agents:
-      queue: "{{matrix}}"
-    env:
-      # See https://playwright.dev/docs/ci#debugging-browser-launches
-      DEBUG: "pw:browser"
+      queue: default
     matrix:
-      - mac
-      #- windows
-    # No notify node because we cannot interpolate the matrix value in the context string
-    # See https://github.com/Automattic/studio/pull/614#discussion_r1821669523
-
-  - group: 📦 Build for Mac
-    key: dev-mac
-    steps:
-      - label: 🔨 Mac Dev Build - {{matrix}}
-        agents:
-          queue: mac
-        command: |
-          .buildkite/commands/prepare-environment.sh
-
-          .buildkite/commands/install-node-dependencies.sh
-
-          node ./scripts/prepare-dev-build-version.mjs
-
-          echo "--- :node: Building Binary"
-          npm run make:macos-{{matrix}}
-
-          # Local trial and error show this needs to run before the DMG generation (obviously) but after the binary has been built
-          echo "--- :hammer: Rebuild fs-attr if necessary before generating DMG"
-          case {{matrix}} in
-            universal | x64)
-              echo "Rebuilding fs-xattr for {{matrix}} architecture"
-              npm rebuild fs-xattr --cpu universal
-              ;;
-            arm64)
-              echo "No need to rebuild fs-xattr because it works out of the box on Apple Silicon"
-              ;;
-            *)
-              echo "^^^ +++ Unexpected architecture {{matrix}}"
-              exit 1
-              ;;
-          esac
-
-          echo "--- :node: Packaging in DMG"
-          npm run make:dmg-{{matrix}}
-
-          echo "--- 📃 Notarizing Binary"
-          bundle exec fastlane notarize_binary
-
-        plugins:
-          - $CI_TOOLKIT_PLUGIN
-          - $NVM_PLUGIN
-        artifact_paths:
-          - out/**/*.app.zip
-          - out/*.dmg
-        matrix:
-          - universal
-          - x64
-          - arm64
-    if: build.tag !~ /^v[0-9]+/
-    # No notify node because we cannot interpolate the matrix value in the context string
-    # See https://github.com/Automattic/studio/pull/614#discussion_r1821669523
-
-  - label: 🔨 Windows Dev Build
-    key: dev-windows
-    command: .buildkite/commands/build-for-windows-dev.ps1
-    artifact_paths:
-      - out\**\studio-setup.exe
-      - out\**\studio-update.nupkg
-      - out\**\RELEASES
-    agents:
-      queue: windows
-    if: build.tag !~ /^v[0-9]+/
+      - "20"
+      - "40"
+      - "60"
     notify:
       - github_commit_status:
-          context: Windows Dev Build
-
-  - label: ":rocket: Distribute Dev Builds"
-    command: |
-      echo "--- :node: Downloading Binaries"
-      buildkite-agent artifact download "*.app.zip" .
-      buildkite-agent artifact download "*.dmg" .
-      buildkite-agent artifact download "*.exe" .
-      buildkite-agent artifact download "*.nupkg" .
-      buildkite-agent artifact download "*\\RELEASES" .
-
-      .buildkite/commands/install-node-dependencies.sh
-
-      echo "--- :node: Generating Release Manifest"
-      IS_DEV_BUILD=true node ./scripts/generate-releases-manifest.mjs
-
-      echo "--- :fastlane: Distributing Dev Builds"
-      install_gems
-      bundle exec fastlane distribute_dev_build
-    artifact_paths:
-      - out/releases.json
-    agents:
-      queue: mac
-    # Using concurrency_group to ensure the CI builds from `trunk` & the git tag, which are likely to run at roughly the
-    # same time, don't run into a race condition when downloading+updating+uploading the `releases.json` file from/to S3
-    concurrency_group: studio/release-manifest-update
-    concurrency: 1
-    concurrency_method: eager
-    depends_on:
-      - step: dev-mac
-      - step: dev-windows
-    plugins:
-      - $CI_TOOLKIT_PLUGIN
-      - $NVM_PLUGIN
-    if: build.branch == 'trunk' && build.tag !~ /^v[0-9]+/
-    notify:
-      - github_commit_status:
-          context: Distribute Dev Builds
-
-  - group: 📦 Build for Mac
-    key: release-mac
-    steps:
-      - label: 🔨 Mac Release Build - {{matrix}}
-        agents:
-          queue: mac
-        command: |
-          .buildkite/commands/prepare-environment.sh
-
-          .buildkite/commands/install-node-dependencies.sh
-          node ./scripts/confirm-tag-matches-version.mjs
-
-          echo "--- :node: Building Binary"
-          npm run make:macos-{{matrix}}
-
-          # Local trial and error show this needs to run before the DMG generation (obviously) but after the binary has been built
-          echo "--- :hammer: Rebuild fs-attr if necessary before generating DMG"
-          case {{matrix}} in
-            universal | x64)
-              echo "Rebuilding fs-xattr for {{matrix}} architecture"
-              npm rebuild fs-xattr --cpu universal
-              ;;
-            arm64)
-              echo "No need to rebuild fs-xattr because it works out of the box on Apple Silicon"
-              ;;
-            *)
-              echo "^^^ +++ Unexpected architecture {{matrix}}"
-              exit 1
-              ;;
-          esac
-
-          echo "--- :node: Packaging in DMG"
-          npm run make:dmg-{{matrix}}
-
-          echo "--- 📃 Notarizing Binary"
-          bundle exec fastlane notarize_binary
-
-        plugins:
-          - $CI_TOOLKIT_PLUGIN
-          - $NVM_PLUGIN
-        artifact_paths:
-          - out/**/*.app.zip
-          - out/*.dmg
-        matrix:
-          - universal
-          - x64
-          - arm64
-        # No notify node because we cannot interpolate the matrix value in the context string
-        # See https://github.com/Automattic/studio/pull/614#discussion_r1821669523
-    if: build.tag =~ /^v[0-9]+/
-
-  - label: 🔨 Windows Release Build
-    key: release-windows
-    command: .buildkite/commands/build-for-windows-release.ps1
-    agents:
-      queue: windows
-    artifact_paths:
-      - out\**\studio-setup.exe
-      - out\**\studio-update.nupkg
-      - out\**\RELEASES
-    if: build.tag =~ /^v[0-9]+/
-    notify:
-      - github_commit_status:
-          context: Windows Release Build
-
-  - label: ":rocket: Publish Release Builds"
-    command: |
-      echo "--- :node: Downloading Binaries"
-      buildkite-agent artifact download "*.zip" .
-      buildkite-agent artifact download "*.dmg" .
-      buildkite-agent artifact download "*.exe" .
-      buildkite-agent artifact download "*.nupkg" .
-      buildkite-agent artifact download "*\\RELEASES" .
-
-      .buildkite/commands/install-node-dependencies.sh
-
-      echo "--- :node: Generating Release Manifest"
-      node ./scripts/generate-releases-manifest.mjs
-
-      echo "--- :fastlane: Distributing Release Builds"
-      install_gems
-      bundle exec fastlane distribute_release_build
-    artifact_paths:
-      - out/releases.json
-    agents:
-      queue: mac
-    # Using concurrency_group to ensure the CI builds from `trunk` & the git tag, which are likely to run at roughly the
-    # same time, don't run into a race condition when downloading+updating+uploading the `releases.json` file from/to S3
-    concurrency_group: studio/release-manifest-update
-    concurrency: 1
-    concurrency_method: eager
-    depends_on:
-      - step: release-mac
-      - step: release-windows
-    plugins:
-      - $CI_TOOLKIT_PLUGIN
-      - $NVM_PLUGIN
-    if: build.tag =~ /^v[0-9]+/
-    notify:
-      - github_commit_status:
-          context: Publish Release Builds
+          context: "Matrix Behavior test"
